export const TIMELINE_EVENT_TYPES = {
  PAYMENT_REQUEST_CREATED: 'PAYMENT_REQUEST_CREATED',
  PAYMENT_CONFIRMATION_SUBMITTED: 'PAYMENT_CONFIRMATION_SUBMITTED',
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED'
};

export const TIMELINE_LABELS_ES = {
  [TIMELINE_EVENT_TYPES.PAYMENT_REQUEST_CREATED]: 'Solicitud de pago creada',
  [TIMELINE_EVENT_TYPES.PAYMENT_CONFIRMATION_SUBMITTED]: 'Ciudadano envió comprobante de pago',
  [TIMELINE_EVENT_TYPES.PAYMENT_APPROVED]: 'Pago aprobado',
  [TIMELINE_EVENT_TYPES.PAYMENT_REJECTED]: 'Pago rechazado'
};
